"""add audit_log table

Revision ID: 15f5f4b754ab
Revises: b5e7f2574b61
Create Date: 2026-08-24 15:54:14.370096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f5f4b754ab'
down_revision: Union[str, Sequence[str], None] = 'b5e7f2574b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('requested_sensitivity', sa.String(), nullable=False),
    sa.Column('resource_sensitivity', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
