"""add content_hash to source_event for idempotent discovery ingestion

Revision ID: 5c4f0a807df8
Revises: 8b75480eceb8
Create Date: 2026-08-24 15:35:07.949085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4f0a807df8'
down_revision: Union[str, Sequence[str], None] = '8b75480eceb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_event', sa.Column('content_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_source_event_content_hash'), 'source_event', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_event_content_hash'), table_name='source_event')
    op.drop_column('source_event', 'content_hash')
    # ### end Alembic commands ###
