"""add source_registry table

Revision ID: 62c6ffdc52e4
Revises: 63864cb0249e
Create Date: 2026-08-24 15:26:09.995569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c6ffdc52e4'
down_revision: Union[str, Sequence[str], None] = '63864cb0249e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_registry',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('authority_tier', sa.Integer(), nullable=False),
    sa.Column('permitted_claim_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('freshness_sla_hours', sa.Integer(), nullable=True),
    sa.Column('pii_classification', sa.String(), nullable=False),
    sa.Column('allowed_for_agent_retrieval', sa.Boolean(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('can_create_accepted_claims', sa.Boolean(), nullable=False),
    sa.Column('policy_note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_registry')
    # ### end Alembic commands ###
