"""add document chunk search/embedding columns and claim raw_record_id

Revision ID: 84f097d63445
Revises: 5c4f0a807df8
Create Date: 2026-08-24 15:43:11.644566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84f097d63445'
down_revision: Union[str, Sequence[str], None] = '5c4f0a807df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('raw_record_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_claim_raw_record_id', 'claim', 'raw_record', ['raw_record_id'], ['id'])
    op.add_column('document_chunk', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True))
    op.add_column('document_chunk', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True))
    op.create_index('ix_document_chunk_search_vector', 'document_chunk', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunk_search_vector', table_name='document_chunk', postgresql_using='gin')
    op.drop_column('document_chunk', 'embedding')
    op.drop_column('document_chunk', 'search_vector')
    op.drop_constraint('fk_claim_raw_record_id', 'claim', type_='foreignkey')
    op.drop_column('claim', 'raw_record_id')
    # ### end Alembic commands ###
