"""add quarantine table and raw_record validation_status

Revision ID: 8b75480eceb8
Revises: ac61eca5ab1c
Create Date: 2026-08-24 15:33:19.829554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b75480eceb8'
down_revision: Union[str, Sequence[str], None] = 'ac61eca5ab1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantine',
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'raw_record',
        sa.Column('validation_status', sa.String(), nullable=False, server_default='pending'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_record', 'validation_status')
    op.drop_table('quarantine')
    # ### end Alembic commands ###
