"""add core knowledge graph tables

Revision ID: ac61eca5ab1c
Revises: 62c6ffdc52e4
Create Date: 2026-08-24 15:29:00.598971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac61eca5ab1c'
down_revision: Union[str, Sequence[str], None] = '62c6ffdc52e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('entity_type', sa.Enum('COMPANY', 'INVESTOR_FIRM', 'PERSON', 'FUND', name='entity_type'), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_canonical_name'), 'entity', ['canonical_name'], unique=False)
    op.create_table('entity_identifier',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_identifier_identifier_value'), 'entity_identifier', ['identifier_value'], unique=False)
    op.create_table('entity_resolution_decision',
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('matched_entity_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.Enum('MATCH', 'NO_MATCH', 'NEEDS_REVIEW', name='resolution_decision_type'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_round',
    sa.Column('company_entity_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('announced_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_funding_round_amount_non_negative'),
    sa.ForeignKeyConstraint(['company_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_run',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_relationship',
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=True),
    sa.Column('to_funding_round_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(to_entity_id IS NOT NULL)::int + (to_funding_round_id IS NOT NULL)::int = 1', name='ck_entity_relationship_single_target'),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['to_funding_round_id'], ['funding_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_record',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_record_content_hash'), 'raw_record', ['content_hash'], unique=False)
    op.create_table('claim',
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_relationship_id', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('claim_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'ACCEPTED', 'DISPUTED', 'SUPERSEDED', 'REJECTED', name='claim_status'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_claim_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_relationship_id'], ['entity_relationship.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('communication_type', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='sensitivity'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('redacted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_record.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_document',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='sensitivity'), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_record.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_content_hash'), 'source_document', ['content_hash'], unique=False)
    op.create_table('source_event',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_record.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_participant',
    sa.Column('communication_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunk',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('document_chunk_id', sa.UUID(), nullable=True),
    sa.Column('text_span', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunk.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence')
    op.drop_table('document_chunk')
    op.drop_table('communication_participant')
    op.drop_table('source_event')
    op.drop_index(op.f('ix_source_document_content_hash'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_table('communication')
    op.drop_table('claim')
    op.drop_index(op.f('ix_raw_record_content_hash'), table_name='raw_record')
    op.drop_table('raw_record')
    op.drop_table('entity_relationship')
    op.drop_table('ingestion_run')
    op.drop_table('funding_round')
    op.drop_table('entity_resolution_decision')
    op.drop_index(op.f('ix_entity_identifier_identifier_value'), table_name='entity_identifier')
    op.drop_table('entity_identifier')
    op.drop_index(op.f('ix_entity_canonical_name'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
